name: License Scanning

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'package-json.lock'
      - 'package.json'
      - '.github/workflows/license-scanning.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --prod
#       - run: yarn install --production --frozen-lockfile
        working-directory: .
      - run: npm install -g node-license-validator
        working-directory: .
      - run: node-license-validator . --allow-licenses Apache-2.0 MIT BSD-2-Clause BSD BSD-3-Clause Unlicense
        working-directory: .